auth:
  jwt:
    secret: ${JWT_SECRET}

  oauth2:
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      auth-uri: https://kauth.kakao.com/oauth/authorize
      redirect-uri: ${SERVER_ADDRESS}/api/v1/auth/kakao/callback
      token-uri: https://kauth.kakao.com/oauth/token
      info-uri: https://kapi.kakao.com/v2/user/me
